apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-argo-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projet-argo
  template:
    metadata:
      labels:
        app: projet-argo
    spec:
      containers:
        - name: projet-argo-container
          image: ynixos/projet-argo:eb85290cfba59162ee0fcdf7faee0bbf68fd8e54
          ports:
            - containerPort: 3000
